### PR TITLE
Undoing of updated JAOPCA

### PR DESCRIPTION
**Pull request by Discomanco**
Still a couple more bugs to find, regarding IC2 autocrafting

### CODE REVIEW

**Review by NielsPilgaard — CHANGES_REQUESTED** [review]
Oof I changed target branch to develop to save us some time, but now there are 4 more files changed... Help 😄

**Comment by Discomanco** [comment]
Oh yeah, those are changes to fix ExNi making Aluminium :P

**Comment by NielsPilgaard** [comment]
So err, are we good to go then? :P

**Comment by Discomanco** [comment]
It should be good to go, yes

**Review by NielsPilgaard — APPROVED** [review]

**Pull request merged**
