### PR TITLE
I think I've done this right? Re-enable the gas intake

### PR DESCRIPTION
**Pull request by MommyHeather**
- Removed the zs code responsible for disabling the gas intake recipe
- Removed the tooltip mentioning the gas intake being disabled / the unpatched dupe
- Add [Finite Gas](https://www.curseforge.com/minecraft/mc-mods/finite-gas) to patch the dupe

I've tested ingame, all seems good, but the amount of stuff that's changed in `minecraftinstance.json` simply for adding one mod has me concerned - is this normal?

### CODE REVIEW

**Comment by Kanzaji** [comment]
> the amount of stuff that's changed in minecraftinstance.json simply for adding one mod has me concerned - is this normal?
From what I know that's normal, CF being CF, and it rewrites a ton of stuff in the file 😅
Tho the best option is to just leave the mod addition to the Disco/Niller when they merge the PR, like I always do for example 😄

**Comment by Discomanco** [comment]
Yeah, adding mods through PRs is basically impossible.
Otherwise the rest is correct - I just need to get back to it eventually :'V

**Comment by MommyHeather** [comment]
Interesting. Would you want me to revert that minecraftinstance.json change?

**Comment by Discomanco** [comment]
Yeah might as well, as it doesn't really do anything

**Comment by MommyHeather** [comment]
That should now be done

**Review by NielsPilgaard — APPROVED** [review]
Thanks!

**Comment by MommyHeather** [comment]
Hehe, just don't forget to add the mod - without it we'd be back at having the dupe and an enabled gas valve

**Pull request merged**
