### PR TITLE
Non-mod changes from V2

### PR DESCRIPTION
**Pull request by Discomanco**
Some ~15 changes, mostly to recipes. Couple that may need a 2nd opinion (BM Meteors / ET Solars).
Apparently my 3 previous PRs also got listed into this, as well as the changes to the serverstart script and workflow.

Draconic Evolution:
 Potentiometer no longer requires Draconium Dust
 Basic Energy Relay and Wireless Crystals are cheaper - requires Pink Slime

Avaritia:
 Skullfire Sword is now significantly cheaper - Stoneblock gave it a bad name by giving it Looting 100
 More interesting recipes for Cosmic Meatballs and Ultimate Stew

Integrated Dynamics:
 Logic Cables now require an XNet Cable to craft, bringing it in line with other cables
 Menril Sapling is now craftable by casting Liquid Blue Slime over an Oak Sapling (Casting Table doesn't support OreDict)

RFTools Dimensions:
 Dimension Builder now needs a max stats Mineralis Celestial Crystal. This gives an alternative to Creative Fluid Tank for infinite resources.

Ice & Fire:
 Dragons Breath is now craftable via the Dragon Forge

Immersive Engineering:
Unbreakable Graphite Electrodes are now craftable. Needs a full durability Graphite Electrode with Titanium Iridium.

Applied Energistics:
 Circuits are now craftable in the AR Precision Assembler, base craft time of 10 ticks. Base parts still needs to be made in inscribers

Creative:
 Replaced RFTools Creative Powercell with EnderIO Creative Capacitor Bank. After the Creative Powercells last change of only generating 1mil RF/t instead of being creative, it is now pretty worthless. Quest and Creative Vending has also been adjusted for this change.

EnderIO:
 Dark Steel Upgrades can now be recycled with NuclearCraft. Also added a more expensive crafting recipe to prior to EnderIOs chapter.

--- The Maybe List ---

Blood Magic:
 Added 5 new meteors.
  - Manganese: The 4 NuclearCraft ores, giving magic renewable source.
  - Space: Contains most spare ores. Low chance of Redstone Clathrates. Needs Moonturf as catalyst. This gives a magic alternative to the Warp Drive, without skipping space completely.
  - Clathrates: Renewable source of Clathrates. Needs Clathrate as catalyst.

Environmental Tech:
 Adjusted Solar Panels to no longer be at their lowest values. With the cost of T5-T6, and the growing knowledge of Mek Turbines, I think this seems reasonable. Following values are for a Tier with full equal Tier solar cells.
Tier | RF/t
T1 | 1152 (2000 goal)
T2 | 8000 (4x previous goal)
T3 | 32112 (4x prev)
T4 | 192430 (6x prev)
T5 | 1152307 (6x prev)
T6 | 9255034 (8x prev)

### CODE REVIEW

**Comment by NillerMedDild** [comment]
All very nice changes 👌 
I can accept the ET change :P

Will you fix the conflicts? :)

**Comment by Discomanco** [comment]
Conflicts fixed :)

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Looks good to me, thanks :D

**Comment by Discomanco** [comment]
Actually need to adjust JEI to show the new Creative Capacitor.
Forgot to mention in the notes that I also changed the Creative Powercell for the Creative Capacitor Bank, as the Creative Powercell is near useless :P

**Comment by NillerMedDild** [comment]
Ah right, another PR incoming then? :P

You didn't forget to mention it though :D

> Creative:
Replaced RFTools Creative Powercell with EnderIO Creative Capacitor Bank. After the Creative Powercells last change of only generating 1mil RF/t instead of being creative, it is now pretty worthless. Quest and Creative Vending has also been adjusted for this change.

**Comment by Discomanco** [comment]
image
:^)
Yeah, another PR will come in tomorrow

**Pull request merged**
