### PR TITLE
1.90g

### PR DESCRIPTION
**Pull request by Discomanco**
Couple hotfixes, one fixing a crash, other fixing problematic recipes.
This is also the patch to introduce SIB to the pack.

Disable Cyclic fluid poison, to make BoPs the default one as it generates in world and causes crashes otherwise
Replace Shifting Star in a few recipes that could be uncraftable on servers with Ender Stars
Made Ender Stars a bit harder to craft, matching Shifting Star slightly

### CODE REVIEW

**Comment by ReiDaTecnologia** [comment]
Wait, why would Cyclic's poison make BoP's poison crash the game? Oredict?

**Comment by NielsPilgaard** [comment]
Err SIB?

**Comment by Discomanco** [comment]
Serialization Is Bad :P

**Comment by NielsPilgaard** [comment]
Ahh yes of course 😅

**Pull request merged**
