### PR TITLE
Update SERVER_GUIDE.txt

### PR DESCRIPTION
**Pull request by OpusC**
remove section on pre-generating the world as the Chunk-Pregenerator (by Speiger) mod was removed in release 1.84

### CODE REVIEW

**Comment by Kanzaji** [comment]
Just a quick note, please target the `develop` branch with this PR 😄

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
Thank you for your contribution 😊 this is fine to go directly to master

**Comment by Kanzaji** [comment]
PR Into the master branch 👀 That's something new 😅

**Comment by Kanzaji** [comment]
Ah alrighty 😄 Yea actually makes sense why now that I think about it.

**Comment by NielsPilgaard** [comment]
Since it's a README update I'd rather have it out now than on next release.

**Pull request merged**
