### PR TITLE
Energy Balancing

### PR DESCRIPTION
**Pull request by Discomanco**
Normalizing energy production to be close to 25M rf/t
Mekanism Turbine: Output reduced by 90%, now caps at 26.74M rf/t
Mekanism Fusion: Output reduced by 33%, now caps at 19.93M rf/t
Popular [Fusion+Turbine setup](https://imgur.com/a/D2nDvRx) can no longer be sustained at max efficiency. Turbine in setup caps at 21.4M rf/t, and Reactor at 4.9M rf/t.
Untouched: Rainbow Generator sits at 25M rf/t, plus tidbits from other generators.
Untouched: NC Fusion, max size D-T reactor makes up to ~26M rf/t
Quantum Compressor: Energy required reduced by 50%. You can still have all 39 Singularities crafting with a single power setup.
ET Solar Panels -again: Too powerful due to miscalculations, output reduced by up-to 70%

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
I like it, I think the Mekanism nerfs are brutal though😄Good to shake up the meta though.

**Review by NielsPilgaard — APPROVED** [review]

**Comment by RaVenInTheDark** [comment]
No MSR love still?

**Comment by Discomanco** [comment]
Mekanism nerfs are brutal, however it was generating 267M rf/t.  
Currently it has potential for 31M rf/t, being the top, if you also draw power from the Fusion Reactor (which the guide doesn't mention)
ET Solar is upto 23M rf/t.

No MSR love, I still don't know exactly what is needed. Saying "This and this modifier could be buffed" unfortunately doesn't help enough

**Comment by NielsPilgaard** [comment]
> Mekanism nerfs are brutal, however it was generating 267M rf/t.
Currently it has potential for 31M rf/t, being the top, if you also draw power from the Fusion Reactor (which the guide doesn't mention)

Yeah, brutal but still a good change :D

**Pull request merged**
