### PR TITLE
Add bat spawn egg recipe to market.

### PR DESCRIPTION
**Pull request by ghatus0**
Did I do this right?

### CODE REVIEW

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
You did! 😄
Thanks for the contribution. I have a vague memory of us intentionally leaving the bat out, but I could be wrong.
@Discomanco do you recall whether we intentionally kept the bat out of the market?

**Comment by Discomanco** [comment]
I really don't :P
We probably just never saw the need

**Comment by Discomanco** [comment]
We may have early on, but at this stage, I don't see a point to keep it out

**Comment by theboo** [comment]
Y'all just wanted to laugh at people trying to punch a bat in a cave with the syringe... Jumping and swinging wildly like a 4yo blindfolded tryina hit a piñata...

**Pull request merged**
